language: python
python:
   - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codev
  - pip install nose

# Run tests
script:
   - coverage run --source app,tests,instance -m pytest   
   - python -m coverage report -m

after_success:
  - coveralls
  
